version: "3.8"

services:
    redis:
        image: redis
        restart: always
    web:
        restart: always
        build:
          context: ./app
        ports:
          - "8000:8000"
        env_file:
          - ./.env.prod
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    worker:
        restart: always
        build:
          context: ./app
        env_file:
          - ./.env.prod
        command: ["celery", "-A", "website", "worker", "-l", "info"]