FROM python:3.9.6-alpine


WORKDIR ./app

RUN python3 -m pip install --upgrade pip
COPY ./requirements.txt .
RUN python3 -m pip install -r requirements.txt


COPY . .


CMD ["python3", "app/manage.py", "runserver", "0.0.0.0:8000"]
